document.write("<form name=fct method='Post' action='http://www.sanmacs.com/mca_information/mca_informa.jsp'>");
document.write("<table border=0 cellspacing=0 cellpadding=0>");
document.write("<tr>");
document.write("<td><p id='ftp' align='justify'>");
document.write("<Select name=university style='font-size:11px'>");
document.write("<option>Search University / Institute</option>");
document.write("<option value=1>Aligarh Muslim University</option>");
document.write("<option value=2>Anna University</option>");
document.write("<option value=3>Banasthali Vidyapith</option>");
document.write("<option value=4>Bharathiar University</option>");
document.write("<option value=5>Bharati Vidyapeeth, Pune</option>");
document.write("<option value=6>Biju Patnaik University</option>");
document.write("<option value=7>BHU University</option>");
document.write("<option value=8>BIT Mesra, Ranchi</option>");
document.write("<option value=9>Cochin University</option>");
document.write("<option value=10>DA-IICT Gandhinagar</option>");
document.write("<option value=11>Delhi University</option>");
document.write("<option value=12>Gurukul Kangri</option>");
document.write("<option value=13>Goa University</option>");
document.write("<option value=14>GJU Hisar</option>");
document.write("<option value=15>GNDU Amritsar</option>");
document.write("<option value=17>IP University</option>");
document.write("<option value=28>IIC, South Campus, Delhi</option>");
document.write("<option value=18>IIT Roorkee</option>");
document.write("<option value=16>Jamia Hamdard University</option>");
document.write("<option value=19>Jamia Millia Islamia</option>");
document.write("<option value=20>Jawaharlal Nehru University</option>");
document.write("<option value=21>MNNIT Allahabad</option>");
document.write("<option value=22>Maharshi Dayanand</option>");
document.write("<option value=23>Madurai Kamaraj</option>");
document.write("<option value=24>NIT Calicut</option>");
document.write("<option value=25>NIT Rourkela</option>");
document.write("<option value=26>NIT Surathkal</option>");
document.write("<option value=27>NIT Trichi</option>");
document.write("<option value=29>Pondicherry University</option>");
document.write("<option value=30>PSG College of Technology</option>");
document.write("<option value=31>PU Chandigarh</option>");
document.write("<option value=32>Punjabi University Patiala</option>");
document.write("<option value=33>SICSR Pune</option>");
document.write("<option value=34>SCIT Pune</option>");
document.write("<option value=35>Tezpur University Assam</option>");
document.write("<option value=36>Thapar Institute of Engg</option>");
document.write("<option value=37>U.P. Technical University</option>");
document.write("<option value=38>Univeristy of Jammu</option>");
document.write("<option value=39>University of Pune</option>");
document.write("<option value=40>University of West Bengal</option>");
document.write("<option value=41>Uttaranchal University</option>");
document.write("<option value=42>University of Hyderabad</option>");
document.write("<option value=43>Veermata Jijabai Tech.</option>");
document.write("<option value=44>Vellore Institute of Tech.</option>");
document.write("</Select>");
document.write("</p></td>");
document.write("<td><img border=0 src='http://www.sanmacs.com/images2/mca_go.gif' onClick='checkt()' style='cursor:hand; margin-left:1px'></img></td>");
document.write("</tr>");
document.write("</table>");
document.write("</form>");
