document.write("<table border=0 cellpadding=3 cellspacing=0>");
document.write("<tr>");
document.write("<th width=6%><a class='new' href='http://www.sanmacs.com/mca_information/all_about_mca/all_about_mca.htm'>MCA ?</a></th>");
document.write("<td><img src='http://www.sanmacs.com/mca_information/mca_informa_images/mca_info_line.gif' width=2 height=32></img></td>");
document.write("<th width=18%><a class='new' href='http://www.sanmacs.com/mca_information/scope_of_mca/scope_of_mca.htm'>Scope of MCA</a></th>");
document.write("<td><img src='http://www.sanmacs.com/mca_information/mca_informa_images/mca_info_line.gif' width=2 height=32></img></td>");
document.write("<th width=20%><a class='new' href='http://www.sanmacs.com/mca_entrance_training/mca_institutes/mca_institutes.htm'>MCA Institutes</a></th>");
document.write("<td><img src='http://www.sanmacs.com/mca_information/mca_informa_images/mca_info_line.gif' width=2 height=32></img></td>");
document.write("<th width=28%><a class='new' href='http://www.sanmacs.com/mca_information/it_sector/career_it.htm'>Successful Career In IT</a></th>");
document.write("<td><img src='http://www.sanmacs.com/mca_information/mca_informa_images/mca_info_line.gif' width=2 height=32></img></td>");
document.write("<th width=29%><a class='new' href='http://www.sanmacs.com/information_for_mca_entrance_students/mca_entrance_test_taking_techniques/mca_entrance_test_taking_techniques.htm'>Test Taking Techniques</a></th>");
document.write("</tr>");
document.write("</table>");